### ISSUE TITLE
pymongo.errors.OperationFailure:text search not enabled

### ISSUE THREAD

**Issue by makflwana** [certsocietegenerale/fame#1]
### Description
Installing fame and getting error mentioned after SSH key generates

### Steps to Reproduce
makflwana@ubuntu:~/fame$ sudo utils/run.sh utils/install.py
[+] Using existing virtualenv.

[+] Installing requirements ...
[?] MongoDB host [localhost]: 
[?] MongoDB port [27017]: 
[?] MongoDB database [fame]: 

Choose your installation type:

 - 1: Web server + local worker
 - 2: Remote worker

[?] Installation type [1]: 1
[?] FAME's URL for users (e.g. https://fame.yourdomain/): https://fame.localhost.com
[+] Creating configuration file ...
[+] SSH key already exists.
Traceback (most recent call last):
  File "utils/install.py", line 227, in <module>
    main()
  File "utils/install.py", line 221, in main
    perform_local_installation(context)
  File "utils/install.py", line 144, in perform_local_installation
    fame_init()
  File "/home/makflwana/fame/fame/core/__init__.py", line 6, in fame_init
    store.connect()
  File "/home/makflwana/fame/fame/core/store.py", line 40, in connect
    self.files.create_index([("$**", TEXT)], background=True)
  File "/home/makflwana/fame/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 1529, in create_index
    self.__create_index(keys, kwargs)
  File "/home/makflwana/fame/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 1437, in __create_index
    sock_info, index, True, False, False, wcn)
  File "/home/makflwana/fame/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 562, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/home/makflwana/fame/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 551, in _insert_one
    self.__write_response_codec_options)
  File "/home/makflwana/fame/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 488, in _legacy_write
    rqst_id, msg, max_size, acknowledged)
  File "/home/makflwana/fame/env/local/lib/python2.7/site-packages/pymongo/pool.py", line 473, in legacy_write
    return helpers._check_gle_response(response)
  File "/home/makflwana/fame/env/local/lib/python2.7/site-packages/pymongo/helpers.py", line 250, in _check_gle_response
    raise OperationFailure(details["err"], code, result)
pymongo.errors.OperationFailure: text search not enable

Also, I am testing the FAME installation on VM.

**Comment by gaelmuller** [comment]
What version of MongoDB are you using ?

MongoDB should be installed following the instructions at https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/ and not with ``apt-get install``.

**Comment by makflwana** [comment]
Yes I manually installed mongodb for Ubuntu 16.04 lts as per documentation and than also getting the same error 

Regards
Kunal M.

**Comment by makflwana** [comment]
Just checked version is 2.4.9

Regards
Kunal M.

**Comment by gaelmuller** [comment]
Something went wrong in your installation. You need to install current version (3.4), which should be the case if you follow the instructions at https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by makflwana** [comment]
Yes but for some reason it's not downloading 3.4. When I do apt-get update - 3 step, I see 3.4.

Than I do apt-get install -y mongodb-org I get error unable to correct problems you have held broken packages.



So I check the packages via dpkg --get-selection | grep hold and no results

So I try with aptitude if install mongodb-org and get following



Thinks mongodb doesn't like me


Regards
Kunal M.

**Comment by gaelmuller** [comment]
This is not really a FAME question, so it is more difficult for us to help
you.

Did you try all solutions at
http://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages
? Seems like your error message is not very useful. Could you paste your
full outputs ?

**Comment by makflwana** [comment]
Was able to fix the issue on fresh install 16.04 LTS.

However, when adding user into database getting following error :+1: 
> db.createUser({ user: "fame", pwd: "passwordgoeshere", roles: [ { role: "dbOwner", db: "fame" } ] })
2017-03-25T00:20:15.080-0700 E QUERY    [thread1] Error: couldn't add user: not authorized on fame to execute command { createUser: "fame", pwd: "xxx", roles: [ { role: "dbOwner", db: "fame" } ], digestPassword: false, writeConcern: { w: "majority", wtimeout: 300000.0 } } :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.createUser@src/mongo/shell/db.js:1290:15
@(shell):1:1

I am asking the question as the creation of user and database is part of pre-requisite, so pretty sure the installation was tested by your team and may have recieved similar error.

**Comment by makflwana** [comment]
have fixed the issue by commenting security out from mongod.conf - installation continued.

**Comment by gaelmuller** [comment]
RBAC should be disabled by default, and the installation documentation says that it should be enabled after creating the users.

On your fresh installation, was RBAC enabled by default ?

**Comment by makflwana** [comment]
The RBAC was enabled after creating users admin and fame as documentation advised.

It didn't work so I disabled the security in the conf file and installation worked perfectly.

Regards
Kunal M.
