### ISSUE TITLE
No initial user account asked.

### ISSUE THREAD

**Issue by Zenithar** [certsocietegenerale/fame#2]
### Description
Where to enter the initial user account 

### Steps to Reproduce
Install from git for a development environment

#### Expected behavior
The administrator guide describes a user account entered during setup process.

#### Actual behavior
No user email or account provided.

########## VERSION ##########

OS: Linux-4.9.16-1-lts-x86_64-with-glibc2.2.5
Python: 2.7.13

########## DEPENDENCIES ###########

alabaster==0.7.10
amqp==2.1.4
androguard==3.0
appdirs==1.4.3
Babel==2.3.4
bamfdetect==1.6.13
beautifulsoup4==4.5.3
billiard==3.5.0.2
bs4==0.0.1
celery==4.0.2
click==6.7
docutils==0.13.1
Flask==0.12
Flask-Classy==0.6.10
Flask-Login==0.3.2
Flask-Negotiation==0.1.9
flask-paginate==0.4.5
future==0.16.0
gitdb2==2.0.0
GitPython==2.1.3
googleplay-api==0.1.0
ijson==2.3
imagesize==0.7.1
itsdangerous==0.24
Jinja2==2.9.5
kombu==4.0.2
markdown2==2.3.3
MarkupSafe==1.0
oletools==0.50
packaging==16.8
pbkdf2==1.3
pefile==2016.3.28
protobuf==3.2.0
pycrypto==2.6.1
Pygments==2.2.0
pymongo==3.4.0
pyparsing==2.2.0
python-magic==0.4.13
pytz==2016.10
rarfile==3.0
requests==2.13.0
six==1.10.0
smmap2==2.0.1
snowballstemmer==1.2.1
Sphinx==1.5.3
sphinx-rtd-theme==0.2.4
sphinxcontrib-httpdomain==1.5.0
vine==1.1.3
volatility==2.6
Werkzeug==0.12.1
yara-python==3.5.0
zxcvbn==1.0

########## MongoDB ##########

Version: 3.4.2
Authorization check: True

########## Configuration ##########

Traceback (most recent call last):
  File "utils/troubleshoot.py", line 83, in <module>
    main()
  File "utils/troubleshoot.py", line 80, in main
    configuration()
  File "utils/troubleshoot.py", line 58, in configuration
    for config in Config.find():
  File "/home/tnormand/Repositories/github/fame/fame/common/mongo_dict.py", line 24, in find
    for obj in objs:
  File "/home/tnormand/Repositories/github/fame/env/lib/python2.7/site-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/home/tnormand/Repositories/github/fame/env/lib/python2.7/site-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/home/tnormand/Repositories/github/fame/env/lib/python2.7/site-packages/pymongo/cursor.py", line 928, in __send_message
    helpers._check_command_response(doc['data'][0])
  File "/home/tnormand/Repositories/github/fame/env/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on fame to execute command { find: "settings", filter: {} }

**Comment by Zenithar** [comment]
I think that `utils/run.sh utils/create_user.py` is just missing from doc.

**Comment by gaelmuller** [comment]
No, ``utils/run.sh utils/create_user.py`` should be called by ``utils/run.sh utils/install.py``.

Could you provide the output you had for the ``utils/run.sh utils/install.py`` command ?

**Comment by Zenithar** [comment]
I flushed the user collection, and rerun the install.py, and this time I had to create an administrator.
