### ISSUE TITLE
Error while running utils/run.sh utils/troubleshoot.py

### ISSUE THREAD

**Issue by FafnerKeyZee** [certsocietegenerale/fame#29]
### Description
Hey, 
When I tried to run utils/troubleshoot.py, I got the following output.

### Debug
fame@fame:~/fame$ utils/run.sh utils/troubleshoot.py
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.12

########## DEPENDENCIES ###########

alabaster==0.7.10
amqp==2.2.1
androguard==3.0.1
Babel==2.4.0
bamfdetect==1.6.13
beautifulsoup4==4.6.0
billiard==3.5.0.3
bs4==0.0.1
celery==4.1.0
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
docutils==0.14
Flask==0.12.2
Flask-Classy==0.6.10
Flask-Login==0.3.2
Flask-Negotiation==0.1.9
flask-paginate==0.5.0
future==0.16.0
gitdb2==2.0.2
GitPython==2.1.5
googleplay-api==0.1.0
idna==2.6
ijson==2.3
imagesize==0.7.1
itsdangerous==0.24
Jinja2==2.9.6
kombu==4.1.0
LEPL==5.1.3
markdown2==2.3.4
MarkupSafe==1.0
oletools==0.51
pbkdf2==1.3
pefile==2017.8.1
protobuf==3.4.0
pycrypto==2.6.1
pyelftools==0.24
Pygments==2.2.0
pymongo==3.5.0
python-magic==0.4.13
pytz==2017.2
rarfile==3.0
requests==2.18.4
rfc6266==0.0.4
six==1.10.0
smmap2==2.0.3
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinx-rtd-theme==0.2.4
sphinxcontrib-httpdomain==1.5.0
sphinxcontrib-websupport==1.0.1
typing==3.6.2
urllib3==1.22
vine==1.1.4
volatility==2.6
Werkzeug==0.12.2
yara-python==3.6.3
zxcvbn==1.0

########## MongoDB ##########

Version: 3.4.7
Authorization check: True

########## Configuration ##########

Traceback (most recent call last):
  File "utils/troubleshoot.py", line 83, in <module>
    main()
  File "utils/troubleshoot.py", line 80, in main
    configuration()
  File "utils/troubleshoot.py", line 58, in configuration
    for config in Config.find():
  File "/home/fame/fame/fame/common/mongo_dict.py", line 24, in find
    for obj in objs:
  File "/home/fame/fame/env/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1134, in next
    if len(self.__data) or self._refresh():
  File "/home/fame/fame/env/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1057, in _refresh
    self.__collation))
  File "/home/fame/fame/env/local/lib/python2.7/site-packages/pymongo/cursor.py", line 949, in __send_message
    helpers._check_command_response(doc['data'][0])
  File "/home/fame/fame/env/local/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on fame to execute command { find: "settings", filter: {} }

**Comment by Heat-Miser** [comment]
Should be fixed now with https://github.com/certsocietegenerale/fame/pull/33
