### ISSUE TITLE
fame installation failed or not running

### ISSUE THREAD

**Issue by agusdwimuladi** [certsocietegenerale/fame#41]
### Description
[i tried fame installation by following tutorial, but i do not know when i want to try to access fame did not work, can anyone help me?
thank you]

### Steps to Reproduce
[Describe the steps to reproduce]

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

**Comment by gaelmuller** [comment]
Could you please fill the template so that we can help you ? We need to know what exact steps you took and what output you had.

**Comment by agusdwimuladi** [comment]
when I try to run fame with utils / run.sh command webserver.py
I got the view:
root@bismillah-VirtualBox:~/fame# utils/run.sh webserver.py
[+] Using existing virtualenv.

 * Serving Flask app "webserver" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:4200/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 245-122-895
127.0.0.1 - - [05/Jun/2018 10:22:29] "GET /analyses/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/fame/env/lib/python2.7/site-packages/flask_classy.py", line 189, in proxy
    response = i.before_request(name, **request.view_args)
  File "/root/fame/web/views/mixins.py", line 20, in before_request
    redir = AuthenticatedView.before_request(self, *args, **kwargs)
  File "/root/fame/web/views/mixins.py", line 12, in before_request
    return current_app.login_manager.unauthorized()
  File "/root/fame/env/lib/python2.7/site-packages/flask_login.py", line 222, in unauthorized
    flash(self.login_message, category=self.login_message_category)
  File "/root/fame/env/lib/python2.7/site-packages/flask/helpers.py", line 410, in flash
    session['_flashes'] = flashes
  File "/root/fame/env/lib/python2.7/site-packages/werkzeug/local.py", line 350, in __setitem__
    self._get_current_object()[key] = value
  File "/root/fame/env/lib/python2.7/site-packages/flask/sessions.py", line 101, in _fail
    raise RuntimeError('The session is unavailable because no secret '
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
127.0.0.1 - - [05/Jun/2018 10:22:29] "GET /analyses/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [05/Jun/2018 10:22:29] "GET /analyses/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Jun/2018 10:22:29] "GET /analyses/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Jun/2018 10:22:30] "GET /analyses/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

and in utils / run.sh worker.py
I got the view:
root@bismillah-VirtualBox:~/fame# utils/run.sh worker.py
[+] Using existing virtualenv.

Traceback (most recent call last):
  File "worker.py", line 231, in <module>
    Worker(queues, args.celery_args, args.refresh_interval).start()
  File "worker.py", line 174, in start
    self.clean_temp_dir()
  File "worker.py", line 152, in clean_temp_dir
    for root, dirs, files in os.walk(fame_config.temp_path, topdown=False):
  File "/root/fame/env/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found
root@bismillah-VirtualBox:~/fame# 


and when i try to access fame
http: // DOMAIN_OR_IP: 4200 /.
I got the look
RuntimeError

RuntimeError: The session is unavailable because no secret key was set. Set the secret_key on the application to something unique and secret.
Traceback (most recent call last)

     File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__

     return self.wsgi_app (environ, start_response)

     File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app

     response = self.handle_exception (e)

     File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception

     reraise (exc_type, exc_value, tb)

     File "/root/fame/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app

     response = self.full_dispatch_request ()

and when I try to access
http: // DOMAIN_OR_IP /.
I do not get the view

**Comment by gaelmuller** [comment]
I think there was an issue during the installation process. Could you `git pull` and rerun the installation script `utils/run.sh utils/install.py` ?

If this does not change anything, could you provide the content of the `conf/fame.conf` file ?

**Comment by agusdwimuladi** [comment]
I tried running the script utils/run.sh utils/install.py and I got orders

[+] Using existing virtualenv.

[+] Installing requirements ...
[?] MongoDB host [localhost]: 127.0.0.1:27017
[?] MongoDB port [27017]: 27017
[?] MongoDB database [fame]: fame
127.0.0.1:27017: [Errno 111] Connection refused

/!\ Could not connect to MongoDB.


2018-06-05 3:45 GMT-04:00 Gael Muller <notifications@github.com>:

**Comment by agusdwimuladi** [comment]
can you help me ?, Your help is very much needed, thank you very much

**Comment by gaelmuller** [comment]
Closing in favor of https://github.com/certsocietegenerale/fame/issues/43
