### ISSUE TITLE
Production Instructions Not Working

### ISSUE THREAD

**Issue by jwidan** [certsocietegenerale/fame#47]
### Description
I am repeatedly receiving errors for the community modules when following the production installation instructions.

### Steps to Reproduce
1. apt-get -qq update
2. apt-get install git python-pip python-dev p7zip-full
3. pip install virtualenv
4. pip install --upgrade pip

5. cp -v /usr/local/bin/pip /usr/bin/pip

6. sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

7. echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

8. apt-get -qq update

9. apt-get install -y mongodb-org

10. systemctl enable mongod
11. systemctl start mongod

12. mongo
```
> use admin
> db.createUser({ user: "admin", pwd: "example", roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] })
> use fame
> db.createUser({ user: "fame", pwd: "example", roles: [ { role: "dbOwner", db: "fame" } ] })
```

13. /etc/mongod.conf
```
security:
  authorization: enabled
```

14. systemctl restart mongod

15. git clone https://github.com/certsocietegenerale/fame
16. cd fame

17. pip install uwsgi

18. /etc/systemd/system/fame_web.service
```
[Unit]
Description=FAME web server

[Service]
Type=simple
ExecStart=/bin/bash -c "cd /fame && uwsgi -H /fame/env --uid root --gid root --socket /tmp/fame.sock --chmod-socket=660 --chown-socket root:www-data -w webserver --callable app"

[Install]
WantedBy=multi-user.target
```

19. /etc/systemd/system
```
[Unit]
Description=FAME workers

[Service]
Type=simple
User=root
ExecStart=/bin/bash -c 'cd /fame && utils/run.sh worker.py'

[Install]
WantedBy=multi-user.target
```

20. utils/run.sh utils/install.py

21. systemctl enable fame_web
22. systemctl enable fame_worker
23. systemctl start fame_web
24. systemctl start fame_worker

25. apt-get install nginx
26. rm /etc/nginx/sites-enabled/default

27. /etc/nginx/sites-available/fame
```
upstream fame {
    server unix:///tmp/fame.sock;
}

server {
    listen 80 default_server;

    # Allows big file upload
    client_max_body_size 0;

    location / {
      include uwsgi_params;
      uwsgi_pass fame;
    }

    location /static/ {
      alias /fame/web/static/;
    }
}
```

28. ln -s /etc/nginx/sites-available/fame /etc/nginx/sites-enabled/fame
29. systemctl restart nginx

#### Expected behavior
All modules should not return any errors and should be in a usable state.

#### Actual behavior
apk_verification, cuckoo, cuckoo_modified, joe, and office_macros all return EnvironmentErrors.
```
/fame/fame/modules/community/processing/apk_verification/requirements.txt: error on 'circle':

Requirement already satisfied: androguard in ./env/lib/python2.7/site-packages (from -r /fame/fame/modules/community/processing/apk_verification/requirements.txt (line 1)) (3.2.1)
Collecting googleplay-api (from -r /fame/fame/modules/community/processing/apk_verification/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d2/74/e089b2d8b9caf88c7738f631a22fee675db6f17d05df9a9ceec99117f601/googleplay_api-0.1.0.tar.gz
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-jACyBx/4bd56651a47a3f4a642aaa5b8ab809c8219f0c6e035325978b12dcc6'
```

```
/fame/fame/modules/community/processing/cuckoo/requirements.txt: error on 'circle':

Collecting ijson (from -r /fame/fame/modules/community/processing/cuckoo/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7f/e9/8508c5f4987ba238a2b169e582c1f70a47272b22a2f1fb06b9318201bb9e/ijson-2.3-py2.py3-none-any.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-jACyBx/af051b681629ce9f0f028b1d3e10f6238379d2a9b8f081e8705190c0'
```

```
/fame/fame/modules/community/processing/cuckoo_modified/requirements.txt: error on 'circle':

Requirement already satisfied: requests in ./env/lib/python2.7/site-packages (from -r /fame/fame/modules/community/processing/cuckoo_modified/requirements.txt (line 1)) (2.18.4)
Collecting ijson (from -r /fame/fame/modules/community/processing/cuckoo_modified/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7f/e9/8508c5f4987ba238a2b169e582c1f70a47272b22a2f1fb06b9318201bb9e/ijson-2.3-py2.py3-none-any.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-jACyBx/af051b681629ce9f0f028b1d3e10f6238379d2a9b8f081e8705190c0'
```

```
/fame/fame/modules/community/processing/joe/requirements.txt: error on 'circle':

Requirement already satisfied: requests in ./env/lib/python2.7/site-packages (from -r /fame/fame/modules/community/processing/joe/requirements.txt (line 1)) (2.18.4)
Collecting ijson (from -r /fame/fame/modules/community/processing/joe/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7f/e9/8508c5f4987ba238a2b169e582c1f70a47272b22a2f1fb06b9318201bb9e/ijson-2.3-py2.py3-none-any.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-jACyBx/af051b681629ce9f0f028b1d3e10f6238379d2a9b8f081e8705190c0'
```

```
/fame/fame/modules/community/processing/office_macros/requirements.txt: error on 'circle':

Collecting oletools (from -r /fame/fame/modules/community/processing/office_macros/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/79/f5/9b1a89145ac9bce77c235fee549fc7af617d778bb29af4c8dd1561813a10/oletools-0.53.1.zip
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-jACyBx/1242e770b9a28f026a448edb32b189c35bb53e95ba2bae9227a930a0'
```

bamfdetect returns an AttributeError.

```
python /fame/fame/modules/community/processing/bamfdetect/install.py: error on 'circle':

Traceback (most recent call last):
  File "/fame/fame/modules/community/processing/bamfdetect/install.py", line 8, in <module>
    main()
  File "/fame/fame/modules/community/processing/bamfdetect/install.py", line 5, in main
    pip.main(['install', '--no-deps', 'git+https://github.com/bwall/bamfdetect#egg=BAMF_Detect'])
AttributeError: 'module' object has no attribute 'main'
```

The other modules do not immediately return an error and I have not tested all of them. The pdf module returns a KeyError, though, when ran against a tested PDF file.

```
2018-07-24 15:44: debug: Trying to queue module 'pdf'
2018-07-24 15:44: debug: Trying to run pdf
2018-07-24 15:44: error: pdf: Could not run on /fame/storage/4daf4edbb04383b93094e89636f303bb11ab687636a4d40813e930c213c3b513/eicar.pdf.
 Traceback (most recent call last):
  File "/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/fame/fame/core/module.py", line 450, in each_with_type
    return self.each(target)
  File "/fame/fame/modules/community/processing/pdf/pdf.py", line 41, in each
    if element['vuln_cve_list']:
KeyError: 'vuln_cve_list'

2018-07-24 15:44: debug: Done with pdf
```

### Debug
```
root@circle:/fame# utils/run.sh utils/troubleshoot.py 
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.12


########## DEPENDENCIES ###########

alabaster==0.7.11
amqp==2.3.2
androguard==3.2.1
asn1crypto==0.24.0
Babel==2.6.0
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
billiard==3.5.0.4
celery==4.1.1
certifi==2018.4.16
chardet==3.0.4
click==6.7
colorama==0.3.9
cycler==0.10.0
decorator==4.3.0
docutils==0.14
enum34==1.1.6
Flask==1.0.2
Flask-Classy==0.6.10
Flask-Login==0.3.2
Flask-Negotiation==0.1.9
flask-paginate==0.5.1
future==0.16.0
gitdb2==2.0.4
GitPython==2.1.11
idna==2.6
imagesize==1.0.0
ipython==5.7.0
ipython-genutils==0.2.0
itsdangerous==0.24
Jinja2==2.10
kiwisolver==1.0.1
kombu==4.2.1
LEPL==5.1.3
lxml==4.2.3
markdown2==2.3.5
MarkupSafe==1.0
matplotlib==2.2.2
networkx==2.1
numpy==1.15.0
packaging==17.1
pathlib2==2.3.2
pexpect==4.6.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.6.0
pyelftools==0.24
Pygments==2.2.0
pymongo==3.6.1
pyparsing==2.2.0
python-dateutil==2.7.3
python-magic==0.4.15
pytz==2018.5
requests==2.18.4
rfc6266==0.0.4
scandir==1.7
simplegeneric==0.8.1
six==1.11.0
smmap2==2.0.4
snowballstemmer==1.2.1
Sphinx==1.7.6
sphinx-rtd-theme==0.3.1
sphinxcontrib-httpdomain==1.6.1
sphinxcontrib-websupport==1.1.0
subprocess32==3.5.2
traitlets==4.3.2
typing==3.6.4
urllib3==1.22
vine==1.1.4
volatility==2.6
wcwidth==0.1.7
Werkzeug==0.14.1
yara-python==3.7.0
zxcvbn==1.0


########## MongoDB ##########

Version: 4.0.0
Authorization check: True

########## Configuration ##########

types: True
virustotal: False
email: False
malware_config: False
volatility: True

Modules:

McAfee                    Antivirus            Disabled   Configured     
Sophos                    Antivirus            Disabled   Configured     
Symantec                  Antivirus            Disabled   Not Configured 
apk                       Processing           Disabled   Configured     
apk_verification          Processing           Disabled   Not Configured 
bamfdetect                Processing           Disabled   Configured     
cuckoo                    Processing           Disabled   Configured     
cuckoo_modified           Processing           Disabled   Configured     
cutthecrap                Processing           Disabled   Not Configured 
eml                       Processing           Disabled   Configured     
joe                       Processing           Disabled   Not Configured 
marcher_config            Processing           Disabled   Configured     
mem_yara                  Processing           Disabled   Not Configured 
office_macros             Processing           Disabled   Configured     
pdf                       Processing           Disabled   Configured     
rat_decoders              Processing           Disabled   Configured     
url_download              Processing           Disabled   Configured     
zip                       Processing           Disabled   Configured     
slack                     Reporting            Disabled   Not Configured 
Yeti                      Threat Intelligence  Disabled   Not Configured 
kvm                       Virtualization       Disabled   Configured     
virtualbox                Virtualization       Disabled   Configured
```

**Comment by udgover** [comment]
Hello,

We are going to check with the same install procedure. Meanwhile, could you detail the behavior when running the in "development" mode after stopping systemd fame_worker and fame_web.

$ utils/run.sh webserver.py
$ utils/run.sh worker.py

Thanks

**Comment by jwidan** [comment]
After stopping systemd fame_worker and fame_web, I ran your commands:

$ utils/run.sh webserver.py
$ utils/run.sh worker.py

The same errors persisted, so I spun up a fresh new Ubuntu 16.04 and tried restarting everything with only the "development" instructions. Once again, the same errors are showing up.

**Comment by jwidan** [comment]
By dropping into the virtualenv shell and manually installing the dependencies, I was able to clear the EnvironmentErrors:

$ source env/bin/activate
(env) $ pip install googleplay-api ijson oletools bs4

I tested the office_macros afterwards which seems to be working now.

The bamfdetect AttributeError remains as well as the KeyError whenever I use the pdf plugin on a PDF embedded with the EICAR test-file.

**Comment by ehrenb** [comment]
I am also having the same issue with bamf (AttributeError, which I suspect is a pip version issue), and EnvironmentErrors for missing directories like /tmp/pip-req-tracker-xxxx.  I attempting to install the workers inside of Docker containers based on Ubuntu 18.04.  Any ideas? I have tried down/upgrading pip.  Errors below:

/fame/fame/modules/community/processing/apk_verification/requirements.txt: error on '430daf905056':

Requirement already satisfied: androguard in ./env/lib/python2.7/site-packages (from -r /fame/fame/modules/community/processing/apk_verification/requirements.txt (line 1)) (3.2.1)
Collecting googleplay-api (from -r /fame/fame/modules/community/processing/apk_verification/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/d2/74/e089b2d8b9caf88c7738f631a22fee675db6f17d05df9a9ceec99117f601/googleplay_api-0.1.0.tar.gz (67kB)
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-7a_0Yv/4bd56651a47a3f4a642aaa5b8ab809c8219f0c6e035325978b12dcc6'


python /fame/fame/modules/community/processing/bamfdetect/install.py: error on '430daf905056':

Traceback (most recent call last):
  File "/fame/fame/modules/community/processing/bamfdetect/install.py", line 8, in <module>
    main()
  File "/fame/fame/modules/community/processing/bamfdetect/install.py", line 5, in main
    pip.main(['install', '--no-deps', 'git+https://github.com/bwall/bamfdetect#egg=BAMF_Detect'])
AttributeError: 'module' object has no attribute 'main'

**Comment by ehrenb** [comment]
The changes made in #52 fixed all of the EnvionmentError issues. FYI.  The bamfdetect module is probably just an outdated version of pip.

**Comment by gaelmuller** [comment]
The bamfdetect issue was fixed as well.
