### ISSUE TITLE
remote worker url_download broke 

### ISSUE THREAD

**Issue by ehrenb** [certsocietegenerale/fame#57]
After enabling the url_download module, files were only downloadable via the local fame worker with the server.  When a remote worker consumed a task to download from the url, the following error occurred:

```python
2018-10-20 21:26: debug: Trying to queue module 'url_download'
2018-10-20 21:26: debug: Trying to run url_download
2018-10-20 21:26: debug: Adding extracted file '/fame/temp/5bd59cca9a6747959a194db4260430e8/com.parental.control.v4.apk'
2018-10-20 21:26: error: url_download: Could not run on http://xxx.xxx.xxx.xxx:8000/com.parental.control.v4.apk.
 Traceback (most recent call last):
  File "/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/fame/fame/core/module.py", line 450, in each_with_type
    return self.each(target)
  File "/fame/fame/modules/community/processing/url_download.py", line 35, in each
    self.add_extracted_file(filepath)
  File "/fame/fame/core/module.py", line 345, in add_extracted_file
    self._analysis.add_extracted_file(location)
  File "/fame/fame/core/analysis.py", line 90, in add_extracted_file
    response = send_file_to_remote(filepath, '/files/')
  File "/fame/fame/common/utils.py", line 74, in send_file_to_remote
    response.raise_for_status()
  File "/fame/env/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://fame:4200/files/

2018-10-20 21:26: debug: Done with url_download
```

The FAME server shows a traceback that indicates the files.py post() view function crashed because it was trying to render a template.  The fame server is trying to render a template that doesn't exist.  This is fixed by adding an "Accept: application/json" header into the requests.post call in send_file_to_remote() in utils.py to indicate that the server should respond to the worker with a JSON encoded payload.

Subsequently, if this change is added in, the core/analysis.py file add_extracted_file() function will need to load the response payload as bson so that it can resolve the File object correctly.  

common/utils.py  
```python
def send_file_to_remote(file, url):
    if isinstance(file, basestring):
        file = open(file, 'rb')

    url = urljoin(fame_config.remote, url)
    response = requests.post(url, files={'file': file}, headers={'X-API-KEY': fame_config.api_key,
                                                                 'Accept': 'application/json'})
    response.raise_for_status()

    file.close()

    return response
```
core/analysis.py 
```python
from bson.json_util import loads
...
    def add_extracted_file(self, filepath):
        self.log('debug', "Adding extracted file '{}'".format(filepath))

        fd = open(filepath, 'rb')
        filename = os.path.basename(filepath)
        f = File(filename=filename, stream=fd, create=False)

        if not f.existing:
            if fame_config.remote:
                response = send_file_to_remote(filepath, '/files/')
                f = File(loads(response.text)['file'])
            else:
                f = File(filename=os.path.basename(filepath), stream=fd)

            f.analyze(self['groups'], self['analyst'], None, self['options'])

        fd.close()

        self.append_to('extracted_files', f['_id'])
        f.add_parent_analysis(self)
```

Hope this helps! I have tested this and it works in my forked version (feel free to pull in that code if these changes seem reasonable)

**Comment by Heat-Miser** [comment]
Hello

can you  please submit a pull request with those modifications ? 

Thank you very much !
