### ISSUE TITLE
FAME worker crash when adding extractions

### ISSUE THREAD

**Issue by lucebac** [certsocietegenerale/fame#61]
### Description
When adding an extraction via "add_extracted_file", the server tries to render the response as a template (maybe because of the renderer precedence, I am not sure about that though). 

Edit:
The template name which is looked for is `.html` and this file obviously does not exist in the template directory. Jinja2 therefore throws an exception and Flask returns a HTTP 500 response.

Consequently, the client cannot decode the error message into the expected `File` object and thus the analysis crashes. Exception traces are provided below.

### Steps to Reproduce
I could only trigger the exception via the zip community module. Just upload a zip file and let fame do its magic (at least one of the files of the zip must not be known to FAME before, otherwise the error will not be triggered).

#### Expected behavior
FAME should not crash.

A pull request will be provided to fix this issue.

#### Exception Traces
Server:
```
[2019-01-09 15:50:17,412] ERROR in app: Exception on /files/ [POST]
Traceback (most recent call last):
  File "/fame/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/fame/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/fame/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/fame/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/fame/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/fame/env/lib/python2.7/site-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "./web/views/helpers.py", line 109, in inner
    return func(*args, **kwargs)
  File "./web/views/files.py", line 122, in post
    return render({'file': f})
  File "/fame/env/lib/python2.7/site-packages/flask_negotiation/__init__.py", line 76, in __call__
    body = renderer.render(data, template, ctx)
  File "/fame/env/lib/python2.7/site-packages/flask_negotiation/renderers.py", line 69, in render
    return render_template(template, **ctx)
  File "/fame/env/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/fame/env/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/fame/env/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/fame/env/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/fame/env/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/fame/env/lib/python2.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/fame/env/lib/python2.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: .html
[pid: 1|app: 0|req: 49/49] 172.18.0.4 () {38 vars in 580 bytes} [Wed Jan  9 15:50:17 2019] POST /files/ => generated 291 bytes in 22 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
```

Client:
```
 Traceback (most recent call last):
  File "/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/fame/fame/core/module.py", line 450, in each_with_type
    return self.each(target)
  File "/fame/fame/modules/FAME community modules/processing/zip.py", line 47, in each
    self.add_extracted_file(filepath)
  File "/fame/fame/core/module.py", line 345, in add_extracted_file
    self._analysis.add_extracted_file(location)
  File "/fame/fame/core/analysis.py", line 90, in add_extracted_file
    response = send_file_to_remote(filepath, '/files/')
  File "/fame/fame/common/utils.py", line 74, in send_file_to_remote
    response.raise_for_status()
  File "/fame/env/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://fame-web:8080/files/
```

**Comment by lucebac** [comment]
Don't know what caused this but it never appeared again.
