### ISSUE TITLE
nothing happens even module has enabled

### ISSUE THREAD

**Issue by jozzytan** [certsocietegenerale/fame#76]
### Description
[Please provide a description of the issue encountered]

### Steps to Reproduce
systemctl start mongod
utils/run.sh utils/install.py
utils/run.sh webserver.py
utils/run.sh worker.py

#### Expected behavior
expecting to see submitted files object was process and analysing

#### Actual behavior
FAME web shows files was input but it doesnt process even with module enabled

![image](https://user-images.githubusercontent.com/56068564/71142391-3fb96a00-2252-11ea-85cc-8127c7000b42.png)

![image](https://user-images.githubusercontent.com/56068564/71142401-48aa3b80-2252-11ea-965a-509abf642a14.png)

![image](https://user-images.githubusercontent.com/56068564/71142427-56f85780-2252-11ea-8cec-f418ed4dd538.png)

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

─$ utils/run.sh utils/troubleshoot.py
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-5.2.0-kali2-amd64-x86_64-with-debian-kali-rolling
Python: 2.7.17

########## DEPENDENCIES ###########

Traceback (most recent call last):
  File "utils/troubleshoot.py", line 87, in <module>
    main()
  File "utils/troubleshoot.py", line 82, in main
    dependencies()
  File "utils/troubleshoot.py", line 29, in dependencies
    pipmain(['freeze'])
TypeError: 'module' object is not callable

**Comment by jozzytan** [comment]
sorry i thought that was enabled. yes i can see selected modules were initiated once enabled. thanks
