### ISSUE TITLE
Could not run on /home/hacker/fame/storage

### ISSUE THREAD

**Issue by jozzytan** [certsocietegenerale/fame#79]
### Description
Could not run on /home/hacker/fame/storage, what could be the issues?

### Steps to Reproduce
2019-12-26 07:49: debug: Trying to queue module 'apk'
2019-12-26 07:49: debug: Trying to queue module 'bamfdetect'
2019-12-26 07:49: debug: Trying to queue module 'cuckoo'
2019-12-26 07:49: debug: Trying to queue module 'cuckoo_modified'
2019-12-26 07:49: debug: Trying to queue module 'cutthecrap'
2019-12-26 07:49: debug: Trying to queue module 'email_headers'
2019-12-26 07:49: debug: Trying to queue module 'eml'
2019-12-26 07:49: debug: Trying to queue module 'msg'
2019-12-26 07:49: debug: Trying to queue module 'office_macros'
2019-12-26 07:49: debug: Trying to queue module 'office_password'
2019-12-26 07:49: debug: Trying to queue module 'rat_decoders'
2019-12-26 07:49: debug: Trying to queue module 'virustotal_public'
2019-12-26 07:49: debug: Trying to queue module 'zip'
2019-12-26 07:49: debug: Trying to run cuckoo_modified
2019-12-26 07:49: debug: Trying to run cuckoo
2019-12-26 07:49: error: cuckoo_modified: Could not run on /home/hacker/fame/storage/2d136860aa264418d1c80725523af7d46347a2122859e953af55955069497f8f/ChromeSetup.exe.
 Traceback (most recent call last):

#### Expected behavior
analysing file submitted

#### Actual behavior
![image](https://user-images.githubusercontent.com/56068564/71459248-858da980-27e1-11ea-9559-26dcdd154cab.png)

### Debug
home/hacker/fame# utils/run.sh utils/troubleshoot.py
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-5.2.0-kali2-amd64-x86_64-with-debian-kali-rolling
Python: 2.7.17

########## DEPENDENCIES ###########

Traceback (most recent call last):
  File "utils/troubleshoot.py", line 87, in <module>
    main()
  File "utils/troubleshoot.py", line 82, in main
    dependencies()
  File "utils/troubleshoot.py", line 29, in dependencies
    pipmain(['freeze'])
TypeError: 'module' object is not callable

**Comment by lucebac** [comment]
It would be interesting to know what exception was thrown for the file. You cut the log output and the screenshot right above that.

**Comment by jozzytan** [comment]
sorry for the delay, i have pasted the whole log. hope that helps. i was very keen to try fame

2019-12-26 09:31: debug: Trying to queue module 'apk'
2019-12-26 09:31: debug: Trying to queue module 'bamfdetect'
2019-12-26 09:31: debug: Trying to queue module 'cuckoo'
2019-12-26 09:31: debug: Trying to queue module 'cuckoo_modified'
2019-12-26 09:31: debug: Trying to queue module 'cutthecrap'
2019-12-26 09:31: debug: Trying to queue module 'email_headers'
2019-12-26 09:31: debug: Trying to queue module 'eml'
2019-12-26 09:31: debug: Trying to queue module 'msg'
2019-12-26 09:31: debug: Trying to queue module 'office_macros'
2019-12-26 09:31: debug: Trying to queue module 'office_password'
2019-12-26 09:31: debug: Trying to queue module 'rat_decoders'
2019-12-26 09:31: debug: Trying to queue module 'virustotal_public'
2019-12-26 09:31: debug: Trying to queue module 'zip'
2019-12-26 09:31: debug: Trying to run cuckoo
2019-12-26 09:31: debug: Trying to run cuckoo_modified
2019-12-26 09:31: error: cuckoo: Could not run on /home/hacker/fame/storage/794e9664e96fd29a9ff056a4eef1e393b1f116afee34c694d912a2deb16110f2/ESA_Rule_Mapping_with_ATT&CK.xlsx.
 Traceback (most recent call last):
  File "/home/hacker/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/hacker/fame/fame/modules/community/processing/cuckoo/cuckoo.py", line 91, in each_with_type
    self.submit_file(target, options)
  File "/home/hacker/fame/fame/modules/community/processing/cuckoo/cuckoo.py", line 126, in submit_file
    response = requests.post(url, files={'file': fp}, data=options)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /tasks/create/file (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a93803b50>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-12-26 09:31: debug: Done with cuckoo
2019-12-26 09:31: error: cuckoo_modified: Could not run on /home/hacker/fame/storage/794e9664e96fd29a9ff056a4eef1e393b1f116afee34c694d912a2deb16110f2/ESA_Rule_Mapping_with_ATT&CK.xlsx.
 Traceback (most recent call last):
  File "/home/hacker/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/hacker/fame/fame/modules/community/processing/cuckoo_modified/cuckoo.py", line 100, in each_with_type
    self.submit_file(target, options)
  File "/home/hacker/fame/fame/modules/community/processing/cuckoo_modified/cuckoo.py", line 138, in submit_file
    response = requests.post(url, files={'file': fp}, data=options)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /tasks/create/file (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a92c98590>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-12-26 09:31: debug: Done with cuckoo_modified
2019-12-26 09:31: debug: Trying to run cutthecrap
2019-12-26 09:31: debug: Trying to run office_macros
2019-12-26 09:31: error: cutthecrap: virtualbox: Missing dependency: VBoxManage
2019-12-26 09:31: debug: Done with office_macros
2019-12-26 09:31: debug: Trying to run virustotal_public
2019-12-26 09:31: error: virustotal_public: Could not run on /home/hacker/fame/storage/794e9664e96fd29a9ff056a4eef1e393b1f116afee34c694d912a2deb16110f2/ESA_Rule_Mapping_with_ATT&CK.xlsx.
 Traceback (most recent call last):
  File "/home/hacker/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/hacker/fame/fame/modules/community/processing/virustotal/virus_total.py", line 63, in each_with_type
    if response['response_code'] == 200 and response['results']['response_code'] == 1:
KeyError: 'response_code'

2019-12-26 09:31: debug: Done with virustotal_public

**Comment by jozzytan** [comment]
screenshot for the fame host

![image](https://user-images.githubusercontent.com/56068564/71573348-6616b980-2b1e-11ea-8898-a50224f2b18b.png)

**Comment by lucebac** [comment]
Your cuckoo_modified module tries to connect to your Cuckoo instance at localhost:8090. Is that correct?

The error with vt_public looks a bit strange but I cannot check the code right now. But it looks like the response from VT cannot be parsed by FAME b/c it seems like in the 'result' dictionary (is it the result JSON from VT?) there is some key missing. Have you had a look into the response from VT to check what is actually responded?

**Comment by jozzytan** [comment]
how can check the cuckoo section? think even the installation doesnt mentions about installing cuckoo. yes i put in my private api for the VT public and that is the culprit, will try to look for a VT public api.   i m keen to try fame but it seems lot more to watch out on the installation, instruction does not seems sufficient on https://fame.readthedocs.io/en/latest/installation.html

**Comment by jozzytan** [comment]
some python issues?

2020-01-06 09:27: debug: Trying to queue module 'apk'
2020-01-06 09:27: debug: Trying to queue module 'bamfdetect'
2020-01-06 09:27: debug: Trying to queue module 'cuckoo'
2020-01-06 09:27: debug: Trying to queue module 'cuckoo_modified'
2020-01-06 09:27: debug: Trying to queue module 'cutthecrap'
2020-01-06 09:27: debug: Trying to queue module 'email_headers'
2020-01-06 09:27: debug: Trying to queue module 'eml'
2020-01-06 09:27: debug: Trying to queue module 'msg'
2020-01-06 09:27: debug: Trying to queue module 'office_macros'
2020-01-06 09:27: debug: Trying to queue module 'office_password'
2020-01-06 09:27: debug: Trying to queue module 'rat_decoders'
2020-01-06 09:27: debug: Trying to queue module 'virustotal_public'
2020-01-06 09:27: debug: Trying to queue module 'zip'
2020-01-06 09:27: debug: Trying to run cuckoo
2020-01-06 09:27: debug: Trying to run cuckoo_modified
2020-01-06 09:27: error: cuckoo: Could not run on youtube.com.
 Traceback (most recent call last):
  **File "/home/hacker/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/hacker/fame/fame/modules/community/processing/cuckoo/cuckoo.py", line 89, in each_with_type
    self.submit_url(target, options)**
  File "/home/hacker/fame/fame/modules/community/processing/cuckoo/cuckoo.py", line 132, in submit_url
    response = requests.post(url, data=options)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /tasks/create/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe76434ed50>: Failed to establish a new connection: [Errno 111] Connection refused',))

2020-01-06 09:27: debug: Done with cuckoo
2020-01-06 09:27: error: cuckoo_modified: Could not run on youtube.com.
 Traceback (most recent call last):
  File "/home/hacker/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/hacker/fame/fame/modules/community/processing/cuckoo_modified/cuckoo.py", line 98, in each_with_type
    self.submit_url(target, options)
  File "/home/hacker/fame/fame/modules/community/processing/cuckoo_modified/cuckoo.py", line 144, in submit_url
    response = requests.post(url, data=options)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/hacker/fame/env/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: /tasks/create/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe764e44ad0>: Failed to establish a new connection: [Errno 111] Connection refused',))

2020-01-06 09:27: debug: Done with cuckoo_modified
2020-01-06 09:27: debug: Trying to run virustotal_public
2020-01-06 09:27: error: virustotal_public: Could not run on youtube.com.
 Traceback (most recent call last):
  File "/home/hacker/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/hacker/fame/fame/modules/community/processing/virustotal/virus_total.py", line 63, in each_with_type
    if response['response_code'] == 200 and response['results']['response_code'] == 1:
KeyError: 'response_code'

2020-01-06 09:27: debug: Done with virustotal_public

**Comment by jozzytan** [comment]
cannot run on storage, are these the VM which is having issues? 

2020-01-06 09:55: debug: Trying to queue module 'apk'
2020-01-06 09:55: debug: Trying to queue module 'bamfdetect'
2020-01-06 09:55: debug: Trying to queue module 'cuckoo'
2020-01-06 09:55: debug: Trying to queue module 'cuckoo_modified'
2020-01-06 09:55: debug: Trying to queue module 'cutthecrap'
2020-01-06 09:55: debug: Trying to queue module 'email_headers'
2020-01-06 09:55: debug: Trying to queue module 'eml'
2020-01-06 09:55: debug: Trying to queue module 'msg'
2020-01-06 09:55: debug: Trying to queue module 'office_macros'
2020-01-06 09:55: debug: Trying to queue module 'office_password'
2020-01-06 09:55: debug: Trying to queue module 'rat_decoders'
2020-01-06 09:55: debug: Trying to queue module 'virustotal_public'
2020-01-06 09:55: debug: Trying to queue module 'zip'
2020-01-06 09:55: debug: Trying to run virustotal_public
**2020-01-06 09:55: error: virustotal_public: Could not run on /home/hacker/fame/storage/10fb512d2fb5e32cf165a85c7b6fc8933159f77aae9c90c3abd6bf34214a25a0/HowToPullLogs.mp4.**
 Traceback (most recent call last):
  File "/home/hacker/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/hacker/fame/fame/modules/community/processing/virustotal/virus_total.py", line 63, in each_with_type
    if response['response_code'] == 200 and response['results']['response_code'] == 1:
KeyError: 'response_code'

2020-01-06 09:55: debug: Done with virustotal_public

**Comment by gaelmuller** [comment]
FAME is a malware analysis framework that relies on modules to perform the actual analysis. The installation instructions only refer to how the tool itself is installed.

If you don't have a Cuckoo Sandbox instance, the `cuckoo` or `cuckoo_modified` modules will not work so you can disable them. If you do have a Cuckoo instance, you should enable one of these modules (depending on which cuckoo version you are using) and make sure the module configuration is correct (see https://fame.readthedocs.io/en/latest/admin.html#modules) to understand how to configure modules.

**Comment by Heat-Miser** [comment]
Like @gaelmuller said, this is not related to FAME. You're missing a cuckoo instance, not installed by fame, to run those plugins.

I'm closing this issue.
