### ISSUE TITLE
Remote workers and nginx 

### ISSUE THREAD

**Issue by 0x7fff9** [certsocietegenerale/fame#8]
Thanks for making FAME available to the community.

### Description
**Issue1:** when trying to run the PROD version of the FE with nginx it outputs a 500.

**nginx_access.log**`x.x.x.x- - [27/Mar/2017:19:44:52 +0200] "GET / HTTP/1.1" 500 32 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0"
`
**nginx_debug.log**
```
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "SERVER_NAME: "
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_HOST: hostname:port"
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0"
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5"
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_ACCEPT_ENCODING: gzip, deflate"
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_COOKIE: session=.COOKIE_STRING"
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_DNT: 1"
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_CONNECTION: keep-alive"
2017/03/27 19:52:52 [debug] 2302#2302: *1 uwsgi param: "HTTP_UPGRADE_INSECURE_REQUESTS: 1"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http cleanup add: 0000561043AC8698
2017/03/27 19:52:52 [debug] 2302#2302: *1 get rr peer, try: 1
2017/03/27 19:52:52 [debug] 2302#2302: *1 stream socket 9
2017/03/27 19:52:52 [debug] 2302#2302: *1 epoll add connection: fd:9 ev:80002005
2017/03/27 19:52:52 [debug] 2302#2302: *1 connect to unix:///tmp/fame.sock, fd:9 #2
2017/03/27 19:52:52 [debug] 2302#2302: *1 connected
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream connect: 0
2017/03/27 19:52:52 [debug] 2302#2302: *1 posix_memalign: 0000561043AA8E40:128 @16
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream send request
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream send request body
2017/03/27 19:52:52 [debug] 2302#2302: *1 chain writer buf fl:0 s:978
2017/03/27 19:52:52 [debug] 2302#2302: *1 chain writer in: 0000561043AC86D0
2017/03/27 19:52:52 [debug] 2302#2302: *1 writev: 978 of 978
2017/03/27 19:52:52 [debug] 2302#2302: *1 chain writer out: 0000000000000000
2017/03/27 19:52:52 [debug] 2302#2302: *1 event timer add: 9: 60000:1490637232929
2017/03/27 19:52:52 [debug] 2302#2302: *1 http finalize request: -4, "/?" a:1, c:2
2017/03/27 19:52:52 [debug] 2302#2302: *1 http request count:2 blk:0
2017/03/27 19:52:52 [debug] 2302#2302: *1 post event 0000561043AEF320
2017/03/27 19:52:52 [debug] 2302#2302: *1 post event 0000561043AEF380
2017/03/27 19:52:52 [debug] 2302#2302: *1 delete posted event 0000561043AEF320
2017/03/27 19:52:52 [debug] 2302#2302: *1 http run request: "/?"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream check client, write event:1, "/"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream recv(): -1 (11: Resource temporarily unavailable)
2017/03/27 19:52:52 [debug] 2302#2302: *1 delete posted event 0000561043AEF380
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream request: "/?"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream dummy handler
2017/03/27 19:52:52 [debug] 2302#2302: *1 post event 0000561043AEF380
2017/03/27 19:52:52 [debug] 2302#2302: *1 delete posted event 0000561043AEF380
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream request: "/?"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream dummy handler
2017/03/27 19:52:52 [debug] 2302#2302: *1 post event 0000561043ADD370
2017/03/27 19:52:52 [debug] 2302#2302: *1 post event 0000561043AEF380
2017/03/27 19:52:52 [debug] 2302#2302: *1 delete posted event 0000561043ADD370
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream request: "/?"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http upstream process header
2017/03/27 19:52:52 [debug] 2302#2302: *1 malloc: 0000561043AAD3F0:4096
2017/03/27 19:52:52 [debug] 2302#2302: *1 recv: fd:9 104 of 4096
2017/03/27 19:52:52 [debug] 2302#2302: *1 http uwsgi status 500 "500 Internal Server Error"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http uwsgi header: "Connection: close"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http uwsgi header: "Content-Type: text/plain"
2017/03/27 19:52:52 [debug] 2302#2302: *1 http uwsgi header done
2017/03/27 19:52:52 [debug] 2302#2302: *1 xslt filter header
2017/03/27 19:52:52 [debug] 2302#2302: *1 HTTP/1.1 500 Internal Server Error
Server: nginx/1.10.0 (Ubuntu)
Date: Mon, 27 Mar 2017 17:52:52 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
```
**Issue2:** when trying to run a remote worker (this time with DEV version because I can't run PROD) I get this on the worker: `500 Server Error: INTERNAL SERVER ERROR for url: http://172.16.20.10:4200/modules/download` I also tried to point the connection to the extranet address I gave to this host but didn't work.

**And this on the server**: 
```
172.16.20.50 - - [27/Mar/2017 20:01:08] "GET /modules/download HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gg/git_code/fame/env/lib/python2.7/site-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/home/gg/git_code/fame/web/views/helpers.py", line 109, in inner
    return func(*args, **kwargs)
  File "/home/gg/git_code/fame/web/views/modules.py", line 448, in download
    f, path = mkstemp(dir=fame_config.temp_path)
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/home/gg/git_code/fame/temp/tmpn3cyU8'
```

### Steps to Reproduce
I have installed FAME as described on the Documentation web page.
I am running a dedicated instance FE for the WEB server, a dedicated instance DB and trying to run a dedicated remote worker instance.
The only step not done from the Documentation is the DB auth (is this critical? I hope this is not the issue.)

### Debug
```root@fame-fe:/home/gg/git_code/fame# utils/run.sh utils/troubleshoot.py
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.12


########## DEPENDENCIES ###########

alabaster==0.7.10
amqp==2.1.4
appdirs==1.4.3
Babel==2.4.0
billiard==3.5.0.2
celery==4.0.2
click==6.7
docutils==0.13.1
Flask==0.12
Flask-Classy==0.6.10
Flask-Login==0.3.2
Flask-Negotiation==0.1.9
flask-paginate==0.4.5
gitdb2==2.0.0
GitPython==2.1.3
imagesize==0.7.1
itsdangerous==0.24
Jinja2==2.9.5
kombu==4.0.2
markdown2==2.3.3
MarkupSafe==1.0
packaging==16.8
Pygments==2.2.0
pymongo==3.4.0
pyparsing==2.2.0
python-magic==0.4.13
pytz==2016.10
requests==2.13.0
six==1.10.0
smmap2==2.0.1
snowballstemmer==1.2.1
Sphinx==1.5.3
sphinx-rtd-theme==0.2.4
sphinxcontrib-httpdomain==1.5.0
vine==1.1.3
Werkzeug==0.12.1
zxcvbn==1.0


########## MongoDB ##########

Version: 3.4.2
Authorization check: True

########## Configuration ##########

types: True
virustotal: False
email: False
malware_config: False
volatility: True

Modules:

McAfee                    Antivirus            Disabled   Configured     
Sophos                    Antivirus            Disabled   Configured     
Symantec                  Antivirus            Disabled   Not Configured 
apk                       Processing           Enabled    Configured     
apk_verification          Processing           Disabled   Not Configured 
bamfdetect                Processing           Enabled    Configured     
cuckoo_modified           Processing           Disabled   Configured     
eml                       Processing           Enabled    Configured     
joe                       Processing           Disabled   Not Configured 
marcher_config            Processing           Disabled   Configured     
mem_yara                  Processing           Enabled    Configured     
office_macros             Processing           Enabled    Configured     
pdf                       Processing           Enabled    Configured     
url_download              Processing           Enabled    Configured     
zip                       Processing           Enabled    Configured     
slack                     Reporting            Disabled   Not Configured 
Yeti                      Threat Intelligence  Disabled   Not Configured 
```

Could you please help me?

Thanks!
regards.
Guido.

**Comment by gaelmuller** [comment]
First of all, thank you for using the template!

**Regarding your setup**

MongoDB authentication is not mandatory, it is your choice. You should only be aware of the security implications.

One thing I would like to mention is that you **need** a local worker for FAME to work properly. If you do not want any analysis to be done of the web server, you can launch a worker that will only take care of module management:

```
$ utils/run.sh worker.py updates
```

**Issue 1**

Could you please provide the stack trace from the web server logs. On a production setup, you can access these logs using the following command:

```
$ sudo journalctl -u fame_web
```

**Issue 2**

My bad. This was fixed in ad3085768866f598308d2559eea13d6f2ad8dafb

**Comment by 0x7fff9** [comment]
Hi!
thanks a lot! sorry for not coming back earlier.

I will test this ASAP and let you know the outcome.

cheers,
Guido.

**Comment by gaelmuller** [comment]
Closing this issue. Do not hesitate to reopen if needed.
