### ISSUE TITLE
Error updating via utils/run.sh utils/update.py

### ISSUE THREAD

**Issue by jdkirk2** [certsocietegenerale/fame#99]
### Description
Attempting to update with sudo utils/run.sh utils/update.py gives the following error:

```
sudo utils/run.sh utils/update.py
[+] Using existing virtualenv.

[+] Updating repository ...
[+] Updating requirements ...
Traceback (most recent call last):
  File "utils/update.py", line 47, in <module>
    main()
  File "utils/update.py", line 41, in main
    create_initial_data()
  File "/home/fame/fame/utils/initial_data.py", line 143, in create_initial_data
    create_types()
  File "/home/fame/fame/utils/initial_data.py", line 13, in create_types
    types = Config.get(name='types')
  File "/home/fame/fame/fame/common/mongo_dict.py", line 29, in get
    obj = klass.get_collection().find_one(kwargs)
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/collection.py", line 1319, in find_one
    for result in cursor.limit(-1):
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/cursor.py", line 1124, in _refresh
    self.__send_message(q)
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/cursor.py", line 999, in __send_message
    response = client._run_operation_with_response(
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1368, in _run_operation_with_response
    return self._retryable_read(
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1471, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1360, in _cmd
    return server.run_operation_with_response(
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/server.py", line 135, in run_operation_with_response
    _check_command_response(first, sock_info.max_wire_version)
  File "/home/fame/fame/env/lib/python3.8/site-packages/pymongo/helpers.py", line 164, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: command find requires authentication, full error: {'ok': 0.0, 'errmsg': 'command find requires authentication', 'code': 13, 'codeName': 'Unauthorized'}


```

**Comment by gaelmuller** [comment]
I tried to fix this. Could you please `git pull` and then relaunch `utils/run.sh utils/update.py` ? (`sudo` should not be necessary in most cases)

**Comment by Augustin-FL** [comment]
Hi,

I do confirm `utils/update.py` work well now when having mongoDB authentication enabled.

I'll close this issue for now. Feel free to re-open it if needed !
